@startuml
scale 600 width

state INITIAL {
    INITIAL: Filling user data
}

state EMAIL_VERIFICATION {
    EMAIL_VERIFICATION : Email verification
}

state PHONE_VERIFICATION {
    PHONE_VERIFICATION : Phone verification
}

state SELECT_IDENTIFICATION_METHOD {
    SELECT_IDENTIFICATION_METHOD : Select identification method
}

state FAST_IDENTIFICATION {
    FAST_IDENTIFICATION: Request identification information \n from another system
}

state DATA_REQUESTED {
    DATA_REQUESTED : Waiting response
}

state FULL_IDENTIFICATION {
    FULL_IDENTIFICATION : Uploading photo with passport \n details for verification
}

state PHOTO_VERIFICATION {
    PHOTO_VERIFICATION : Photo with passport details verification
}

state BLACKLIST_CHECKING {
    BLACKLIST_CHECKING : Blacklist checking
}

state COMPLETED {
    COMPLETED : Registration completed
}

state BLOCKED {
    BLOCKED : Registration completed \n with blocking
}


INITIAL --> EMAIL_VERIFICATION : NEW_USER_SAVED

EMAIL_VERIFICATION --> PHONE_VERIFICATION : EMAIL_CONFIRMED

PHONE_VERIFICATION --> SELECT_IDENTIFICATION_METHOD : PHONE_CONFIRMED

SELECT_IDENTIFICATION_METHOD ---> FAST_IDENTIFICATION : SELECT_FAST_IDENTIFICATION
SELECT_IDENTIFICATION_METHOD ---> FULL_IDENTIFICATION : SELECT_FULL_IDENTIFICATION

FAST_IDENTIFICATION ---> SELECT_IDENTIFICATION_METHOD : CANCEL_SELECTION
FAST_IDENTIFICATION ---> DATA_REQUESTED : SEND_DATA_REQUEST

DATA_REQUESTED ---> SELECT_IDENTIFICATION_METHOD : FAILED_ANSWER
DATA_REQUESTED --> COMPLETED : SUCCESSFUL_ANSWER

FULL_IDENTIFICATION ---> SELECT_IDENTIFICATION_METHOD : CANCEL_SELECTION
FULL_IDENTIFICATION --> PHOTO_VERIFICATION : PHOTO_UPLOADED

PHOTO_VERIFICATION --> FULL_IDENTIFICATION : FAILED_PHOTO_VERIFICATION
PHOTO_VERIFICATION --> BLACKLIST_CHECKING : PHOTO_CONFIRMED

BLACKLIST_CHECKING --> COMPLETED : SUCCESSFUL_CHECK
BLACKLIST_CHECKING --> BLOCKED : FAILED_CHECK

@enduml