networks:
  caching_network:
    driver: bridge

services:
  postgresql:
    container_name: db-postgresql
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_user_123
      POSTGRES_DB: test_database
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ../../../data/postgresql/data:/var/lib/postgresql/data
      - ./sql/postgresql/init_postgresql_database.sql:/docker-entrypoint-initdb.d/init_postgresql_database.sql
    command: >
      postgres -c shared_preload_libraries=pg_stat_statements
    networks:
      - caching_network

  couchbase:
    container_name: db-couchbase
    image: couchbase
    restart: unless-stopped
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: test_user
      COUCHBASE_ADMINISTRATOR_PASSWORD: test_user_123
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    volumes:
      - ../../../data/couchbase:/opt/couchbase/var
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://db-couchbase:8091" ]
      interval: 5s
      retries: 10
      start_period: 10s
    networks:
      - caching_network

  couchbase-init:
    container_name: couchbase-init
    image: couchbase
    depends_on:
      couchbase:
        condition: service_healthy
    command: >
      sh -c '
      /opt/couchbase/bin/couchbase-cli cluster-init
      --cluster db-couchbase
      --cluster-username test_user
      --cluster-password test_user_123
      --services data,index,query
      --cluster-ramsize 512
      --index-storage-setting default;
      /opt/couchbase/bin/couchbase-cli bucket-create
      --cluster db-couchbase:8091
      --username test_user
      --password test_user_123
      --bucket test_bucket
      --bucket-type couchbase
      --bucket-ramsize 256;
      '
    networks:
      - caching_network

  hazelcast:
    container_name: db-hazelcast
    image: hazelcast/hazelcast
    restart: unless-stopped
    environment:
      - HZ_NETWORK_PUBLICADDRESS=localhost:5701
      - HZ_CLUSTERNAME=test-cluster
    ports:
      - "5701:5701"
    volumes:
      - ./config/hazelcast.xml:/opt/hazelcast/config/hazelcast.xml
    networks:
      - caching_network

  redis:
    container_name: db-redis
    image: redis
    restart: unless-stopped
    command: redis-server --requirepass test_user_123 --save "" --appendonly no
    ports:
      - "6379:6379"
    volumes:
      - ../../../data/redis:/data
    networks:
      - caching_network