networks:
  mssql_network:
    driver: bridge

services:
  mssql:
    container_name: db-mssql
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    environment:
      SA_PASSWORD: sa_user_123
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - ../../../data/mssql:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD", "/opt/mssql-tools/bin/sqlcmd",
          "-U", "sa",
          "-P", "sa_user_123",
          "-Q", "SELECT 1"
        ]
      interval: 10s
      retries: 5
      start_period: 20s
    networks:
      - mssql_network

  mssql-init:
    image: mcr.microsoft.com/mssql/server
    network_mode: service:mssql
    command: >
      bash -c '
        for file in ./docker-entrypoint-initdb.d/*.sql; do
          echo "Executing SQL file $$file"
          until /opt/mssql-tools/bin/sqlcmd \
            -U sa -P sa_user_123 \
            -v DatabaseName=test_database \
            -v SchemaName=test_schema \
            -v LoginName=test_user \
            -v Password=TestUser#123 \
            -i "$$file" > /dev/null; do
            echo "Retry SQL execution for $$file"
            sleep 1
          done
        done
        exit 0
      '
    volumes:
      - ./sql/mssql/init_mssql_database.sql:/docker-entrypoint-initdb.d/init_mssql_database.sql
    depends_on:
      mssql:
        condition: service_healthy