networks:
  mariadb_first_network:
    driver: bridge
  mariadb_second_network:
    driver: bridge

services:
  first_mariadb:
    container_name: first_mariadb
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: testRoot123
      MYSQL_DATABASE: multiple_data_sources
      MYSQL_USER: first_test_user
      MYSQL_PASSWORD: test_User_123
    ports:
      - "3306:3306"
    volumes:
      - ../../../data/first_mariadb:/var/lib/mysql
#      - ./sql/mariadb/001_create_table_type_value.sql:/docker-entrypoint-initdb.d/001_create_table_type_value.sql
#      - ./sql/mariadb/002_datasource_first_insert.sql:/docker-entrypoint-initdb.d/002_datasource_first_insert.sql
    networks:
      - mariadb_first_network

  second_mariadb:
    container_name: second_mariadb
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: testRoot321
      MYSQL_DATABASE: multiple_data_sources
      MYSQL_USER: second_test_user
      MYSQL_PASSWORD: test_User_123
    ports:
      - "3307:3306"
    volumes:
      - ../../../data/second_mariadb:/var/lib/mysql
#      - ./sql/mariadb/001_create_table_type_value.sql:/docker-entrypoint-initdb.d/001_create_table_type_value.sql
#      - ./sql/mariadb/002_datasource_second_insert.sql:/docker-entrypoint-initdb.d/002_datasource_second_insert.sql
    networks:
      - mariadb_second_network