package com.fedorizvekov.statemachine.model.enums;

public enum RegistrationEvent {

    NEW_USER_SAVED,
    EMAIL_CONFIRMED,
    PHONE_CONFIRMED,
    SELECT_FAST_IDENTIFICATION,
    SELECT_FULL_IDENTIFICATION,
    CANCEL_SELECTION,
    SEND_DATA_REQUEST,
    FAILED_ANSWER,
    SUCCESSFUL_ANSWER,
    PHOTO_UPLOADED,
    FAILED_PHOTO_VERIFICATION,
    PHOTO_CONFIRMED,
    SUCCESSFUL_CHECK,
    FAILED_CHECK

}
