server:
  port: 8081

logging:
  pattern:
    console: "%magenta(%d) %highlight(%-5level)[%cyan(%t)] %yellow(%logger{1.}): - %msg%n%throwable"
  level:
    com.fedorizvekov.db.mariadb.multipledatasources: INFO
    org.springframework: INFO