server:
  port: 8081

mariadb:
  datasource:
    url: jdbc:mariadb://localhost:3306/multiple_data_sources
    username: test_user
    password: test_User_123
    driver-class-name: org.mariadb.jdbc.Driver
  hibernate:
    dialect: org.hibernate.dialect.MariaDBDialect

second:
  mariadb:
    datasource:
      url: jdbc:mariadb://localhost:3307/multiple_data_sources
      username: second_test_user
      password: test_User_123
      driver-class-name: org.mariadb.jdbc.Driver

hibernate:
  hbm2ddl:
    auto: validate

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

logging:
  pattern:
    console: "%magenta(%d) %highlight(%-5level)[%cyan(%t)] %yellow(%logger{1.}): - %msg%n%throwable"
  level:
    com.fedorizvekov.db.mariadb.multipledatasources: INFO
    org.springframework: INFO
    com.zaxxer.hikari.HikariConfig: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
    org.hibernate.hql: INFO