ALTER SESSION SET CONTAINER=test_database;
ALTER SESSION SET CURRENT_SCHEMA=TEST_USER;

DROP SEQUENCE IF EXISTS type_value_long_id_seq;

CREATE SEQUENCE type_value_long_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCYCLE;
