server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/query_jpa
    username: test_user
    password: test_User_123
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

logging:
  pattern:
    console: "%magenta(%d) %highlight(%-5level)[%cyan(%t)] %yellow(%logger{1.}): - %msg%n%throwable"
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO