networks:
  mariadb_network:
    driver: bridge

services:
  maria_db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: testRoot123
      MYSQL_DATABASE: query_jpa
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_User_123
    ports:
      - "3306:3306"
    volumes:
      - ../../../data/mariadb:/var/lib/mysql
    networks:
      - mariadb_network