server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database?allowPublicKeyRetrieval=true&useSSL=false
    username: test_user
    password: test_user_123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

logging:
  pattern:
    console: "%magenta(%d) %highlight(%-5level)[%cyan(%t)] %yellow(%logger{1.}): - %msg%n%throwable"
  level:
    com.fedorizvekov.db.mysql: INFO
    org.springframework: INFO
    com.zaxxer.hikari.HikariConfig: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
    org.hibernate.hql: INFO