networks:
  postgresql_network:
    driver: bridge

services:
  postgresql:
    container_name: postgresql
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_User_123
      POSTGRES_DB: query_data_rest
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ../../../data/postgresql/data:/var/lib/postgresql/data
    networks:
      - postgresql_network