server:
  port: 8087

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/query_data_rest?currentSchema=test_schema
    username: test_user
    password: test_User_123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: test_schema
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

logging:
  pattern:
    console: "%magenta(%d) %highlight(%-5level)[%cyan(%t)] %yellow(%logger{1.}): - %msg%n%throwable"
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO